spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: merchant-service-route
              uri: lb://merchant-service
              predicates:
                - Path=/api/merchant/**
            - id: payment-service-route
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**
            - id: ledger-service-route
              uri: lb://ledger-service
              predicates:
                - Path=/api/ledger/**
            - id: settlement-service-route
              uri: lb://settlement-service
              predicates:
                - Path=/api/settlements/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info
